=== vladlep/passctema4/horoscop.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="students">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="student" maxOccurs="unbounded">
        <xs:complexType>       
		<xs:attribute name="nr_matr" type="xs:integer" use="required"/>
		<xs:attribute name="nume" type="xs:string" use="required"/>
    <xs:attribute name="medie" type="xs:double" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== vladlep/passctema4/trunk/horoscop.xml
<?xml version="1.0" encoding="UTF-8" ?> 
<students  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="I:\vlad\serios\java\passc4\horoscop.xsd">
	<student nr_matr="1" nume="Vlad" medie="9" />
	<student nr_matr="2" nume="Maria" medie="8" />
	<student nr_matr="3" nume="Mircea" medie="8"  > </student>
	<student nr_matr="4" nume="Nr4" medie="8" />
	<student nr_matr="5" nume="Nr5" medie="9.5" />
	<student nr_matr="6" nume="Nr5" medie="5" />
	<student nr_matr="7" nume="Nr6" medie="6.5" /> 
</students>
